nelmio_api_doc:
  documentation:
    info:
      title: Todos App
      description: Todos app made in Symfony.
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/(?!api/doc$)(?!_error.*$) # Accepts any routes under / except /api/doc and /_error.*
